# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: true
check_commit_message: false
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: false
deploy_client_to_rubygems: false
deploy_daily_client_to_pypi: false
deploy_daily_client_to_rubygems: false
deploy_to_pypi: false
docker_fixtures: false
docs_test: true
plugin_app_label: gem
plugin_camel: PulpGem
plugin_camel_short: Gem
plugin_caps: PULP_GEM
plugin_caps_short: GEM
plugin_dash: pulp-gem
plugin_dash_short: gem
plugin_name: pulp_gem
plugin_snake: pulp_gem
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pydocstyle: true
pypi_username: None
stable_branch: null
test_bindings: false
test_performance: false
travis_addtl_services: []
travis_notifications: None

